### PR TITLE
Navigation and Viewport adjustments

### PR DESCRIPTION
**Pull request by FreaKzero**
Referring to: https://github.com/bower/bower.github.io/issues/189

Tested with Android Tablet/Phone and with iOS Simulator
Desktop: Chrome, Firefox, Safari

bildschirmfoto 2016-03-26 um 11 05 10
bildschirmfoto 2016-03-26 um 11 05 23
bildschirmfoto 2016-03-26 um 11 05 27
bildschirmfoto 2016-03-26 um 11 05 33
screenshot_2016-03-26-10-12-42
screenshot_2016-03-26-10-12-55

### CODE REVIEW

**Comment by BenMann** [comment]
Thanks for the PR!
ping @desandro, your territory ;)

**Comment by desandro** [comment]
LGTM

**Comment by FreaKzero** [comment]
@desandro @BenMann 
Im also willed to unify the statspage but there i would have some questions before i begin:
Should it be really "unified" ? (Title left aligned - somehow should be done because there wouldnt be a space for the navigation otherwise)
Should i tighten up the viewports like i did in the searchpage ? (3 viewports instead of 2)
Since the statuspage uses other frameworks/tech i would need to modify the HTML heavily so i ask this beforehand.

Can also do the brandred banner for the Mainsite.

**Comment by sheerun** [comment]
I think the same top bar at all pages is good enough for "unified".

It would be best to move all pages into single repository.. For now I'm just merging this PR.

**Pull request merged**
