### PR TITLE
Add grunt packages to ignore list

### PR DESCRIPTION
**Pull request by davidjbradshaw**
Remove grunt packages from search results, as these should be installed via npm, not bower.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Don't change the indentation.

**Comment by davidjbradshaw** [comment]
Ops sorry that was Sublime, didn't notice.

**Comment by davidjbradshaw** [comment]
One tab rather than four space yeah?

**Comment by sindresorhus** [comment]
Why? It was already squash merged.

**Pull request merged**
